### ISSUE TITLE
Bug: Telegram uploading is not working properly.

### ISSUE THREAD

**Issue by X-Uchiha** [Sam-Max/Rclone-Tg-Bot#11]
### There is a problem uploading zip file to telegram. 

**When I leech zip file of upload max size it creates a new zip file of the existing zip file. I am uploading a zip file of 6GB on telegram it should be spilt as `file.zip.001 file.zip.002 file.zip.003` but bot uploads it as `file.zip.zip.001 file.zip.zip.002 file.zip.zip.003`**

**Comment by Sam-Max** [comment]
> 

Thanks bro for your words. I had surgery a few days ago, and have covid also. I will see that problem as soon as I can.

**Comment by X-Uchiha** [comment]
thanks bro, Wishing you a speedy recovery.

**Comment by Sam-Max** [comment]
> 
Analysing the issue, the problem is that the file you want to upload is already a zip file, and the bot splits that zip file into another zip because of upload max size and 7z tool cannot split a file without a format like .zip

**Comment by Sam-Max** [comment]
> thanks bro, Wishing you a speedy recovery.

Analysing the issue, the problem is that the file you want to upload is already a zip file, and the bot splits that zip file into another zip because of upload max size and 7z tool cannot split a file without a format like .zip
