### ISSUE TITLE
Any way to deploy it on Github Action.

### ISSUE THREAD

**Issue by hackevil** [Sam-Max/Rclone-Tg-Bot#14]
Hey is it possible to deploy t on github action, where we get free vm, since it is banned on heroku and others PaaS.
Here is a refrence for Github Action workflow - https://github.com/hitesh920/GhostMirror-Workflow-v2

**Comment by Sam-Max** [comment]
> Hey is it possible to deploy t on github action, where we get free vm, since it is banned on heroku and others PaaS. Here is a refrence for Github Action workflow - https://github.com/hitesh920/GhostMirror-Workflow-v2

You can deploy on heroku now

**Comment by hackevil** [comment]
wont heroku ban me? i have already lost my 2 cc added heroku accounts, thats why i was asking if it can be deployed on github actions
