### ISSUE TITLE
Unable to load Rclone

### ISSUE THREAD

**Issue by hackevil** [Sam-Max/Rclone-Tg-Bot#15]
Hey i successfully deployed the master branch, but i am unable to add rclone configs in it.
Also, do i need to keep the first line of rclone.conf file.

My rclone.conf file looks like this.

[Onedrive]
type = onedrive
client_id = xyz	
client_secret = 12345
token = {"access_token":"123xyz"}
drive_id = b!AWkpb6haR0OuWlRa2
drive_type = business

and my variable RCLONE_CONFIG looks like

RCLONE_CONFIG = "[Onedrive]
type = onedrive
client_id = xyz	
client_secret = 12345
token = {"access_token":"123xyz"}
drive_id = b!AWkpb6haR0OuWlRa2
drive_type = business
"

the format is right?

i was using the above format but the app threw some error, i have attached the error logs below.
https://gist.github.com/hackevil/a48564cde157f8901458003bf5a20857

**Comment by Sam-Max** [comment]
> Use single quotation marks not double, like this:   

RCLONE_CONFIG = '[Onedrive]
type = onedrive
client_id = xyz
client_secret = 12345
token = {"access_token":"123xyz"}
drive_id = b!AWkpb6haR0OuWlRa2
drive_type = business
'

**Comment by arjung24** [comment]
What will be the format for multiple rclone config??
It would be helpful if u write down the format for multiple rclone config. Thanks.
