### ISSUE TITLE
/qbmirror does not work

### ISSUE THREAD

**Issue by hackevil** [Sam-Max/Rclone-Tg-Bot#17]
Pretty much the title.
I have attached the logs below.
![Capture](https://user-images.githubusercontent.com/23115256/180666300-c919a47b-8d46-46af-9803-e17937e59316.PNG)

https://gist.github.com/hackevil/d13376ae3907d55b629e2a989655504c

**Comment by hackevil** [comment]
> > Pretty much the title. I have attached the logs below. ![Capture](https://user-images.githubusercontent.com/23115256/180666300-c919a47b-8d46-46af-9803-e17937e59316.PNG)
> > https://gist.github.com/hackevil/d13376ae3907d55b629e2a989655504c
> 
> Yes, only problem with magnets, I forgot to implement code.

Ohk.

**Comment by Sam-Max** [comment]
> > > Pretty much the title. I have attached the logs below. ![Capture](https://user-images.githubusercontent.com/23115256/180666300-c919a47b-8d46-46af-9803-e17937e59316.PNG)
> > > https://gist.github.com/hackevil/d13376ae3907d55b629e2a989655504c
> > 
> > 
> > Yes, only problem with magnets, I forgot to implement code.
> 
> Ohk.

fixed

**Comment by hackevil** [comment]
will try it out soon

**Comment by hackevil** [comment]
Getting this error

2022-07-25 21:33:48,017 INFO MainThread root Rclone file loaded!!
2022-07-25 21:33:48,578 INFO MainThread bot Initializing Aria2c
2022-07-25 21:34:14,23[9](https://github.com/doloresjose/slam-work/runs/7509032688?check_suite_focus=true#step:7:10) INFO MainThread bot MEGA_API_KEY not provided!
2022-07-25 21:34:15,741 ERROR MainThread bot One or more env variables missing! Exiting now
2022-07-25 21:34:15,830 ERROR MainThread asyncio Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb42173fdf0>
Error: Process completed with exit code 1.

![image](https://user-images.githubusercontent.com/23115256/180878255-5e67c2ae-4c9a-4398-99c4-d4d1bd66c468.png)

i have filled the mandatory variables

**Comment by Sam-Max** [comment]
> Getting this error
> 
> 2022-07-25 21:33:48,017 INFO MainThread root Rclone file loaded!! 2022-07-25 21:33:48,578 INFO MainThread bot Initializing Aria2c 2022-07-25 21:34:14,23[9](https://github.com/doloresjose/slam-work/runs/7509032688?check_suite_focus=true#step:7:10) INFO MainThread bot MEGA_API_KEY not provided! 2022-07-25 21:34:15,741 ERROR MainThread bot One or more env variables missing! Exiting now 2022-07-25 21:34:15,830 ERROR MainThread asyncio Unclosed client session client_session: <aiohttp.client.ClientSession object at 0x7fb42173fdf0> Error: Process completed with exit code 1.
> 
> ![image](https://user-images.githubusercontent.com/23115256/180878255-5e67c2ae-4c9a-4398-99c4-d4d1bd66c468.png)
> 
> i have filled the mandatory variables

your API_ID is wrong, it has letter and numbers, and it must be only numbers.
