### ISSUE TITLE
Few Missing Features.

### ISSUE THREAD

**Issue by hackevil** [Sam-Max/Rclone-Tg-Bot#18]
**1.Shareable files and folders link.**

- When /myfiles is used, it list files and when a file is selected it only shows its name & delete option, it would be nice to have link along with it and also give a delete option for folder too, it will be very tiring process to delete each files individually.

- Message containing link of file/folder when leeching/mirroring is completed.

![image](https://user-images.githubusercontent.com/23115256/181100883-53de1075-f4aa-45a5-bfb1-9c6e508118bc.png)

**2. Status Command**
- A status command is must, coz when bunch of friend use bot it is very hard to find msg of leech/mirror files, we have to scroll a lot to find the exact msg
- A better option would be to ha an auto updating status message for all running tasks, which should be updated  at certain interval and then it would msg new status after the interval while deleting the old status of all tasks.

**3. A better Upload status message.**

- Its very vanilla and does not match with the download status format, it should be like the download status message, same stands for /leech command status.

![image](https://user-images.githubusercontent.com/23115256/181111159-e4e01264-688d-4f44-bd28-882e701bde35.png)

**Few tweaks for /leech command**

- When /leech command is used, the telegram files are uploaded and presented as it is, and if there is large no of files in a folder and is leeched it uploads a lot of files and sends it, which is a mess to manage and looks very cluttered, so i thing there should be and option for "/leechzip and /leechunzip", which would declutter the chat a lot and '/leechunzip' would be nice to have if you we need to upload the contents of and zipped file, unzipped to telegram.
- Lets say if folder has lots of files in it, and when /leech command is used on it it uploads tons of files and send it to the chat. Now we have lots of files in our chat, now it will be again a lot of hassle for the user to manage/find the file if he need to find it few days later. So i think the bot should send a message containing all list of files name with hyperlink to the files in a single message. so that the user can save the on message containing all the links instead of remembering/scrolling to the 100s of files he leeched to telegram. I have attached the 2nd screenshot below for reference.
![image](https://user-images.githubusercontent.com/23115256/181115378-04ac65a4-9dc1-4ad7-9b19-dd7edd6617de.png)
![image](https://user-images.githubusercontent.com/23115256/181119828-a07de48a-ffad-42e4-8480-144aee606ced.png)

**4.File selection for /qbmirror**

- Add file selection for qbittoreent.

I may add more suggestion later, right now i can only think of these.

Also make an telegram group for more discussion about features and their implementation.

**Comment by Sam-Max** [comment]
You can already delete folders on /myfiles menu. Just click on any folder (not the root one), and click on Folder Settings.

**Comment by Sam-Max** [comment]
and thanks for your suggestions, I will try to implement new things over time, but this is a hobby for me and working alone.

**Comment by hackevil** [comment]
> You can already delete folders on /myfiles menu. Just click on any folder (not the root directory), and click on Folder Settings.

thx found the button in "Folder Setting" menu.



> and thanks for your suggestions, I will try to implement new things over time, but this is a hobby and a learning experience for me, and I am doing this alone.

Sure, this is a new project and it will take some time to mature, i am just happy it is not just another clone of Ansaty repo.

**Comment by hackevil** [comment]
Few more bugs.

The upload speed are terrible compared to what i am getting on /speedtest result.
![image](https://user-images.githubusercontent.com/23115256/181371025-9310c295-87a0-488c-bdf7-20c891ffeebd.png)

- There is bug in the status msg, the file name shows some random digits instead of the "Name"
![image](https://user-images.githubusercontent.com/23115256/181371311-162ef892-95e9-41dc-b753-3244d838ae3a.png)

**Comment by Sam-Max** [comment]
Maybe cloud where you are uploading to, has a upload bandwith limit.
