### ISSUE TITLE
add better ui sir

### ISSUE THREAD

**Issue by gsweeh** [Sam-Max/Rclone-Tg-Bot#2]
like this
![68747470733a2f2f74656c656772612e70682f66696c652f6538383661346331313666663663343762636466612e6a7067](https://user-images.githubusercontent.com/65717972/159342293-9a3e104c-e9eb-4a20-bf55-ccd1aa820336.jpeg)
![68747470733a2f2f74656c656772612e70682f66696c652f3166316639336334643535643766366333336664392e6a7067](https://user-images.githubusercontent.com/65717972/159342302-8f063b8d-41fa-4448-8476-e51597e155e8.jpeg)
![68747470733a2f2f74656c656772612e70682f66696c652f6135356364363733626565326238653233373832632e6a7067](https://user-images.githubusercontent.com/65717972/159342307-cdd55a39-3539-4d13-9d23-14ed6ebf3106.jpeg)

**Comment by Sam-Max** [comment]
> like this ![68747470733a2f2f74656c656772612e70682f66696c652f6538383661346331313666663663343762636466612e6a7067](https://user-images.githubusercontent.com/65717972/159342293-9a3e104c-e9eb-4a20-bf55-ccd1aa820336.jpeg) ![68747470733a2f2f74656c656772612e70682f66696c652f3166316639336334643535643766366333336664392e6a7067](https://user-images.githubusercontent.com/65717972/159342302-8f063b8d-41fa-4448-8476-e51597e155e8.jpeg) ![68747470733a2f2f74656c656772612e70682f66696c652f6135356364363733626565326238653233373832632e6a7067](https://user-images.githubusercontent.com/65717972/159342307-cdd55a39-3539-4d13-9d23-14ed6ebf3106.jpeg)

I will make some improvements...

**Comment by Sam-Max** [comment]
I will make some improvements but not exactly like those pictures
