### ISSUE TITLE
Bot randomly restarts mid download

### ISSUE THREAD

**Issue by phantomic12** [Sam-Max/Rclone-Tg-Bot#20]
I was leeching a 100gb file with not a lot of seeders, and out of nowhere I see the uptime message from the bot, and the download stops moving. I assume this isn't a code issue, rather a heroku issue. Does anyone know about this issue and possibly how to circumvent it? Only real issue I have with the bit itself is that each download has its own message, which with many concurrent downloads can be a bit of a chore to keep track of. Otherwise, great bot, keep up the great work!

**Comment by Sam-Max** [comment]
> 

Don´t know what may be causing that. Next time send logs.
