### ISSUE TITLE
task status stuck bug

### ISSUE THREAD

**Issue by b1fly** [Sam-Max/Rclone-Tg-Bot#27]
I'm back again, when the task is uploading rclone, it has actually been uploaded, but the task status is still displayed in the upload, it seems to be stuck, this may be a bug.
![image](https://user-images.githubusercontent.com/108970034/184464874-b7893d93-70fe-415c-9538-52f81b1a5d20.png)

**Comment by Sam-Max** [comment]
It will be fixed on next update

**Comment by b1fly** [comment]
> It will be fixed on next update

thanks bro

**Comment by b1fly** [comment]
> It will be fixed on next update

Bro, how to customize BT Tracker for qbittorrent

**Comment by Sam-Max** [comment]
> > It will be fixed on next update
> 
> Bro, how to customize BT Tracker for qbittorrent
I really don't know, I've never looked into it
