### ISSUE TITLE
Progress message lags far behind actual progress

### ISSUE THREAD

**Issue by leomarmol03** [Sam-Max/Rclone-Tg-Bot#3]

**Comment by Sam-Max** [comment]
> _No description provided._

Progress message updates every 10 seconds and gets its values from Rclone tool

**Comment by leomarmol03** [comment]
if I already saw I put it in 1 second and I improve a lot!

**Comment by Sam-Max** [comment]
> if I already saw I put it in 1 second and I improve a lot!

The problem is that if you set it less than 10 seconds when you use bot on a telegram group you will get FloodWait error from telegram
