### ISSUE TITLE
Couldn't go to next page when select a remote

### ISSUE THREAD

**Issue by jackthenewbie** [Sam-Max/Rclone-Tg-Bot#32]
`2022-09-06 04:38:22,339 INFO MainThread pyrogram.session.session [1] Retrying "messages.EditMessage" due to TimeoutError()`
there is a lot logs like this

**Comment by Sam-Max** [comment]
> `2022-09-06 04:38:22,339 INFO MainThread pyrogram.session.session [1] Retrying "messages.EditMessage" due to TimeoutError()` there is a lot logs like this

Not happening to me. Make sure to update bot and send full logs next time

**Comment by jackthenewbie** [comment]
> > `2022-09-06 04:38:22,339 INFO MainThread pyrogram.session.session [1] Retrying "messages.EditMessage" due to TimeoutError()` there is a lot logs like this
> 
> Not happening to me. Make sure to update bot and send full logs next time

`2022-09-17 17:15:24,423 ERROR MainThread pyrogram.dispatcher next_page_mirrorset() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
TypeError: next_page_mirrorset() takes 1 positional argument but 2 were given
2022-09-17 17:15:41,452 ERROR MainThread pyrogram.dispatcher next_page_mirrorset() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
TypeError: next_page_mirrorset() takes 1 positional argument but 2 were given`

Will this help?
