### ISSUE TITLE
Bug Report with logs and ss attached 

### ISSUE THREAD

**Issue by bolavefasfas** [Sam-Max/Rclone-Tg-Bot#33]
My config 

![image](https://user-images.githubusercontent.com/82230241/188873321-ea4527cf-5c0e-438a-b92c-60b8a2a65241.png)
 Should I keep port number 80 or keep it blank 

1. Qbit download not working
![image](https://user-images.githubusercontent.com/82230241/188863558-aab8afc2-9b85-46ad-ab78-66847436497d.png)

 - its stuck here  

2. Copy menu does not close  

![image](https://user-images.githubusercontent.com/82230241/188872198-68bc368e-226b-43cc-aaf6-5fc958a30537.png)

 - `app_1  | 2022-09-07 11:53:48,006 ERROR MainThread pyrogram.dispatcher 'CallbackQuery' object has no attribute 'delete'
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
app_1  |     await handler.callback(self.client, *args)
app_1  |   File "/usr/src/app/bot/modules/copy.py", line 229, in copy_menu_settings
app_1  |     await query.delete()
app_1  | AttributeError: 'CallbackQuery' object has no attribute 'delete'`

**Comment by Sam-Max** [comment]
Keep port number blank by default is 80. And the problem with menus was fixed with the update that I just released. Update bot.

**Comment by bolavefasfas** [comment]
> Keep port number blank by default is 80. And the problem with menus was fixed with the update that I just released. Update bot.

Yo Thanks for reply man 

What about this did you fix this ??
1. Qbit download not working

**Comment by bolavefasfas** [comment]
1. When I **cancel the copy** these errors occur ss and logs attached (Though on tg side it works smoothly for copy but on vps these are the errors)

![image](https://user-images.githubusercontent.com/82230241/189340119-3cba72e3-4242-4b96-a7ec-be8666c1b85e.png)

![image](https://user-images.githubusercontent.com/82230241/189340286-89caf2bd-2296-49b3-9519-ced10949c8e4.png)

```
app_1  | 2022-09-09 11:27:40,900 ERROR MainThread pyrogram.dispatcher Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
app_1  |     await handler.callback(self.client, *args)
app_1  |   File "/usr/src/app/bot/modules/copy.py", line 208, in copy_menu_callback
app_1  |     await query.answer()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 159, in answer
app_1  |     return await self._client.answer_callback_query(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/bots/answer_callback_query.py", line 71, in answer_callback_query
app_1  |     return await self.invoke(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
app_1  |     r = await self.session.invoke(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 361, in invoke
app_1  |     return await self.send(query, timeout=timeout)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 331, in send
app_1  |     RPCError.raise_it(result, type(data))
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
app_1  |     raise getattr(
app_1  | pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
app_1  | 2
```

These above are the logs when copy is cancelled 

2. These are the errors after **completing the copy** 

![image](https://user-images.githubusercontent.com/82230241/189340892-362a7585-62cb-4cf4-b55d-61d4ecc9aa49.png)

![image](https://user-images.githubusercontent.com/82230241/189341097-6de5f3f7-8b3d-45ce-a091-534bd3713d92.png)

```

app_1  | 2022-09-09 11:31:07,161 ERROR MainThread pyrogram.dispatcher Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
app_1  | Traceback (most recent call last):
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
app_1  |     await handler.callback(self.client, *args)
app_1  |   File "/usr/src/app/bot/modules/copy.py", line 208, in copy_menu_callback
app_1  |     await query.answer()
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/types/bots_and_keyboards/callback_query.py", line 159, in answer
app_1  |     return await self._client.answer_callback_query(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/bots/answer_callback_query.py", line 71, in answer_callback_query
app_1  |     return await self.invoke(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
app_1  |     r = await self.session.invoke(
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 361, in invoke
app_1  |     return await self.send(query, timeout=timeout)
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 331, in send
app_1  |     RPCError.raise_it(result, type(data))
app_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
app_1  |     raise getattr(
app_1  | pyrogram.errors.exceptions.bad_request_400.QueryIdInvalid: Telegram says: [400 QUERY_ID_INVALID] - The callback query id is invalid (caused by "messages.SetBotCallbackAnswer")
```

These above errors occur after copy is completed 

3. All the rclone remotes are shown **twice** in the **/myfiles** but you can see they are just once clearly in /mirrorset 

![image](https://user-images.githubusercontent.com/82230241/189341591-2c48186a-21f8-4f1b-b364-3a5aad1e252d.png)

4. The Cup is 100 % for most of the time I am using Dedicated vps for this Rclone Bot 

Though I have set this in qbit config 
`Queueing\MaxActiveDownloads=50
Queueing\MaxActiveTorrents=10
Queueing\MaxActiveUploads=10
Downloads\DiskWriteCacheSize=30`

The cpu usage hasnt reduced 

**Vps Specs**
- 2gb ram + 1 gb swap
- 1 core, 1 thread Dedicated 
- 1 tb storage hdd 120 Mbps hdd read write speed 

Can you add a var to set custom core like 1 or 2 depending on vps choice or what would you suggest so that cpu usage will go down like 80-90 % is fine any more modifications ?

5. **Feature Request**
1.  A button to add custom rclone flags for /copy 

 button because to change flags from bot every time no need to edit .py file manually

**Comment by Sam-Max** [comment]
@bolavefasfas bolavefasfas
1. Qbit working fine now. 
2. Fixed error shown when cancel the copy and after completing the copy
3. Fixed shown twice in the /myfiles.

**Comment by bolavefasfas** [comment]
> @bolavefasfas bolavefasfas
> 
> 1. Qbit working fine now.
> 2. Fixed error shown when cancel the copy and after completing the copy
> 3. Fixed shown twice in the /myfiles.
> 4. Try set limit for MaxConnecs, decrease AsyncIOThreadsCount and set limit of DiskWriteCacheSize to 32.
> 5. Maybe in future, I add custom rclone flags

- Bot does not work in group try sending rclone.conf in group 

- it works in private but not in grp even after authorizing you want me to send me the video of problem ??

**Comment by Sam-Max** [comment]
> 

Yes, I know

**Comment by Sam-Max** [comment]
> > @bolavefasfas bolavefasfas
> > 
> > 1. Qbit working fine now.
> > 2. Fixed error shown when cancel the copy and after completing the copy
> > 3. Fixed shown twice in the /myfiles.
> > 4. Try set limit for MaxConnecs, decrease AsyncIOThreadsCount and set limit of DiskWriteCacheSize to 32.
> > 5. Maybe in future, I add custom rclone flags
> 
>     * Bot does not work in group try sending rclone.conf in group
> 
>     * it works in private but not in grp even after authorizing you want me to send me the video of problem ??

Yes, I know
