### ISSUE TITLE
Heroku Dont Like This One

### ISSUE THREAD

**Issue by saikrishnaegcc2** [Sam-Max/Rclone-Tg-Bot#34]
I tried to depoly this repo in heroku.. after few min heroku banning my account any solution

**Comment by Sam-Max** [comment]
> I tried to depoly this repo in heroku.. after few min heroku banning my account any solution

Heroku won't be free any more from November

**Comment by saikrishnaegcc2** [comment]
is there any free cloud servece like heroku which is support to depoloy

**Comment by CosmosCloudX** [comment]
> is there any free cloud servece like heroku which is support to depoloy

We cant tell as it’s against tos
