### ISSUE TITLE
Where to place rclone.conf if I dont want to upload it from bot & feature request 

### ISSUE THREAD

**Issue by bolavefasfas** [Sam-Max/Rclone-Tg-Bot#36]
- Where to place rclone.conf in repo? if I dont want to upload it from bot 
- gclone does not work properly 
- can you add gdtot support ?
- Direct link to telegram option "can you add this"

**Comment by Sam-Max** [comment]
> * Where to place rclone.conf in repo? if I dont want to upload it from bot
> 
>     * gclone does not work properly
> 
>     * can you add gdtot support ?
> 
>     * Direct link to telegram option "can you add this"

rclone.conf is saved on a folder called users, with a subfolder with the user id

**Comment by bolavefasfas** [comment]
So it would be in my github repo in rootof repo create /users/214242345"myuserid" and if multiple users it would be /user/userid2 and similar for userid 3 and so right number right??"
Ik about gclone permissions thanks

**Comment by bolavefasfas** [comment]
Yp /users/userid worked properly thanks

**Comment by killerlearner** [comment]
Where can I upload global config in repo or any config to set
