### ISSUE TITLE
Couldn't edit message

### ISSUE THREAD

**Issue by jackthenewbie** [Sam-Max/Rclone-Tg-Bot#37]
https://logpaste.com/ZiTPzJIZ
#32 similar as this one right here.

**Comment by Sam-Max** [comment]
> https://logpaste.com/ZiTPzJIZ #32 similar as this one right here.

Yes, issue with mirrorset when clicking on next will be fixed on next update

**Comment by Sam-Max** [comment]
> https://logpaste.com/ZiTPzJIZ #32 similar as this one right here.

fixed

**Comment by jackthenewbie** [comment]
https://logpaste.com/Bfo6VfuZ
This happen after downloaded, I'm trying with another torrent. Will update later.

**Comment by Sam-Max** [comment]
> https://logpaste.com/YDJJAHpw This happen after downloaded, I'm trying with another torrent. Will update later.
> 
> > > https://logpaste.com/ZiTPzJIZ #32 similar as this one right here.
> > 
> > 
> > fixed
> 
> And this one is indeed fixed. Thanks. However I encouner another one, logs post above
> 
> Edit-2:Tried with another torrent, there is error with completed edit message

Update bot, you a re using old version

**Comment by jackthenewbie** [comment]
https://logpaste.com/kuHajc9E
Still couldn't edit message with latest version this is all the output, will update later after a restart:)

**Comment by Sam-Max** [comment]
> 

Redeploy from scratch

**Comment by Sam-Max** [comment]
> https://logpaste.com/kuHajc9E Still couldn't edit message with latest version this is all the output, will update later after a restart:)

Redeploy from scratch, and the log shows speed test not running

**Comment by jackthenewbie** [comment]
> > https://logpaste.com/kuHajc9E Still couldn't edit message with latest version this is all the output, will update later after a restart:)
> 
> Redeploy from scratch, and the log shows speed test not running because vps not allowing

https://pastelog.netlify.app/logs/d0effcb0-4030-11ed-b11c-6df6683bff72
here, already remove container and redeploy, still couldn't show finished messages (stuck at 99.67%)

**Comment by Sam-Max** [comment]
> > > https://logpaste.com/kuHajc9E Still couldn't edit message with latest version this is all the output, will update later after a restart:)
> > 
> > 
> > Redeploy from scratch, and the log shows speed test not running because vps not allowing
> 
> https://pastelog.netlify.app/logs/d0effcb0-4030-11ed-b11c-6df6683bff72 here, already remove container and redeploy, still couldn't show finished messages (stuck at 99.67%)

Try now

**Comment by jackthenewbie** [comment]
New update fixed, thanks!:)
