### ISSUE TITLE
leech error

### ISSUE THREAD

**Issue by b1fly** [Sam-Max/Rclone-Tg-Bot#39]
Mirroring MKV video files from the cloud to telegram does not display the video content, only displays the title
I am a telegram member, and I set TG_SPLIT_SIZE= "4294967296" in the config configuration file
![image](https://user-images.githubusercontent.com/108970034/190911387-c21e20a0-4c78-495e-823a-efdfb1859455.png)

**Comment by Sam-Max** [comment]
@b1fly when using string session for 4gb upload don't use bot, only group

**Comment by b1fly** [comment]
> TG_SPLIT_SIZE



> @b1fly when using string session for 4gb upload don't use bot, only group. And you don´t need to set TG_SPLIT_SIZE= "4294967296" in the config, as the bot will automaticly set the value if you are premium user.

allright . So I need to clear the value of TG_SPLIT_SIZE?

**Comment by b1fly** [comment]
> > > TG_SPLIT_SIZE
> > 
> > 
> > > @b1fly when using string session for 4gb upload don't use bot, only group. And you don´t need to set TG_SPLIT_SIZE= "4294967296" in the config, as the bot will automaticly set the value if you are premium user.
> > 
> > 
> > allright . So I need to clear the value of TG_SPLIT_SIZE?
> 
> yes

Get restricted messages from private channels.

I don't understand how this works
