### ISSUE TITLE
Can you add "--ignore-existing" flag in copy.py

### ISSUE THREAD

**Issue by bolavefasfas** [Sam-Max/Rclone-Tg-Bot#41]
can you add this flag in copy function for rclone `--ignore-existing` this one it would be helpful to avoid copying duplicate files.
Or point the line number where I can add it please ?

**Comment by b1fly** [comment]
/copy The command result of copying cloud to cloud shows error. I copied onedrive to onedrive, but gdrive is displayed.
![image](https://user-images.githubusercontent.com/108970034/191559045-a2e0de3f-642a-4f6d-b340-0070726e78dc.png)

**Comment by Sam-Max** [comment]
> 

--ignore-existing will make rclone unconditionally skip all files that exist on the destination, but copy command on bot creates a new folder on destination with the content from origin, so don't see why use that.

**Comment by Sam-Max** [comment]
> /copy The command result of copying cloud to cloud shows error. I copied onedrive to onedrive, but gdrive is displayed. ![image](https://user-images.githubusercontent.com/108970034/191559045-a2e0de3f-642a-4f6d-b340-0070726e78dc.png)

It should be only the name of the button, but the actual link should be from one drive as rclone generates the link depending on selected cloud.

**Comment by bolavefasfas** [comment]
> 

I don't want duplicates in the folder that's why can you tell me which lined do I need to modify to add --ignore-existing  please
line number and 1 ss where to add flag will be enough or line link 
It is useful when the bot is run on services which restart after sometime so like previous copy is incomplete and next copy will copy files again which are already copied if the flag is used it will skip those files and start copying from where it left .
As vps are expensive I am using it for other docker images for rr family

**Comment by bolavefasfas** [comment]
> > 
> 
> --ignore-existing will make rclone unconditionally skip all files that exist on the destination, but copy command on bot creates a new folder on destination with the content from origin, so don't see why use that flag.

I don't want duplicates in the folder that's why can you tell me which lined do I need to modify to add --ignore-existing please
line number and 1 ss where to add flag will be enough or line link
It is useful when the bot is run on services which restart after sometime so like previous copy is incomplete and next copy will copy files again which are already copied if the flag is used it will skip those files and start copying from where it left .
As vps are expensive I am using it for other docker images for rr family

**Comment by Sam-Max** [comment]
> 

ok, I understand know the situation.

**Comment by bolavefasfas** [comment]
> > 
> 
> Ok, I understand know your problem. On rclone_copy.py change line 20.
> 
> Before: cmd = ['rclone', 'copy', f'--config={conf_path}', f'{origin_drive}:{origin_dir}', f'{dest_drive}:{dest_dir}{origin_dir}', '-P']
> 
> After: cmd = ['rclone', 'copy', "--ignore-existing", f'--config={conf_path}', f'{origin_drive}:{origin_dir}', f'{dest_drive}:{dest_dir}{origin_dir}', '-P']

Thanks It worked But if their are many files it kind of seems stuck which it is actually not its just ignoring files in background 
If its possible can you add status like in gclone bot from msgsuite for ignoring files not an necessity just add it in future tasks if possible.

**Comment by b1fly** [comment]
> > 
> 
> **Thanks It worked.**

I copied 205.9GB of files to my onedrive, but when I used the /copy command to leave it there for one night, I found that the task status was stuck, not updated, resulting in incomplete file copying, and it stopped 9 hours ago , can this problem be solved? Otherwise, it will cause repeated starts when copying a large number of files.

![image](https://user-images.githubusercontent.com/108970034/192079564-41990cb0-31c0-4240-af62-af78dcb925c9.png)
![image](https://user-images.githubusercontent.com/108970034/192079572-5cb6e1dd-5e93-44eb-b8b5-0d886c95bca3.png)

**Comment by Sam-Max** [comment]
> > > 
> > 
> > 
> > Ok, I understand know your problem. On rclone_copy.py change line 20.
> > Before: cmd = ['rclone', 'copy', f'--config={conf_path}', f'{origin_drive}:{origin_dir}', f'{dest_drive}:{dest_dir}{origin_dir}', '-P']
> > After: cmd = ['rclone', 'copy', "--ignore-existing", f'--config={conf_path}', f'{origin_drive}:{origin_dir}', f'{dest_drive}:{dest_dir}{origin_dir}', '-P']
> 
> **Thanks It worked.** 1.It works for a particular file or a subfolder perfectly 2. If I try to Clone Complete Team Drive it throws this error as it google doesn't allow to share team drive root url with api ![image](https://user-images.githubusercontent.com/82230241/192070791-dba0e187-45b2-45b6-969f-0b26d2df686a.png)
> 
>     3. if its a root drive can you disable Cloud link ? or any other solution

That seems to be a limitation of google api, so I don't think that cannot be bypass

**Comment by Sam-Max** [comment]
> 

Next time send logs to check

**Comment by bolavefasfas** [comment]
> > 
> 
> @bolavefasfas Next time send logs to check copy issue

Their was no error in logs 
Just check the image attached below out once you will understand what's the issue 

![image](https://user-images.githubusercontent.com/82230241/192156163-8d3951e2-b736-4e24-9411-1ae0854b9b5f.png)
