### ISSUE TITLE
status bug

### ISSUE THREAD

**Issue by b1fly** [Sam-Max/Rclone-Tg-Bot#42]
I don't know if this is a bug. It has appeared twice, and the status has not been updated, causing the file to be copied from the cloud to the cloud to be interrupted.If you copy large-capacity files, if this problem occurs, it is very painful, because you have to start from scratch and cannot continue
![image](https://user-images.githubusercontent.com/108970034/191693015-8f6446e7-49f8-4405-ac6c-5d69832dcf5b.png)
![image](https://user-images.githubusercontent.com/108970034/191693159-a70f32ab-d561-4110-9c48-d8f35aea7d8c.png)

**Comment by b1fly** [comment]
2022-09-22 11:50:57,916 ERROR MainThread pyrogram.dispatcher 'utf-8' codec can't decode byte 0xe8 in position 79: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/usr/src/app/bot/modules/copy.py", line 208, in copy_menu_callback
    await rclone_copy.copy(origin_drive, origin_dir, dest_drive, dest_dir)
  File "/usr/src/app/bot/helper/mirror_leech_utils/download_utils/rclone/rclone_copy.py", line 24, in copy
    status= await rc_status.start(status_type= MirrorStatus.STATUS_COPYING)
  File "/usr/src/app/bot/helper/mirror_leech_utils/status_utils/rclone_status.py", line 35, in start
    data = self._process.stdout.readline().decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 79: invalid continuation byte

**Comment by b1fly** [comment]
Video files larger than 2GB and smaller than 4GB cannot be uploaded to telegram in the super group.
My guess may be that leech judges the member and then updates the bytes to the environment variable, and there is an error. Although I am a member, the split size bytes in /ownerset will not become 4GB, and the default is to display 2GB bytes. I tried to Manually modify it to 4GB bytes, but video files larger than 2GB still cannot be uploaded to telegram.

![image](https://user-images.githubusercontent.com/108970034/191922823-eb6900be-b905-4b3a-817b-b75a46bc7936.png)
![image](https://user-images.githubusercontent.com/108970034/191922892-a1e8519e-08bc-4a99-849c-dc1f8a68bc7b.png)

**Comment by bolavefasfas** [comment]
> 

[b1fly](https://github.com/b1fly) @b1fly can you send me ur tg username ?

**Comment by Sam-Max** [comment]
> > 
> 
> [b1fly](https://github.com/b1fly) @b1fly can you send me ur tg username ?

Send me yours and I will write you

**Comment by b1fly** [comment]
> 

who?  me? to prevent spam, my telegram does not have a username set

**Comment by b1fly** [comment]
> > > 
> > 
> > 
> > [b1fly](https://github.com/b1fly) @b1fly can you send me ur tg username ?
> 
> Send me yours and I will write you

who?  me? to prevent spam, my telegram does not have a username set

**Comment by Sam-Max** [comment]
> 

Split size is only for now for zipleech, I need to implement for leech alone.

**Comment by b1fly** [comment]
> > 
> 
> @b1fly Did you set string session? By the way split size is only useful for now for zipleech, I need to implement for leech alone.

The problem with premium members uploading files of up to 4GB has been fixed, after I updated the new version you posted.

Just today I logged into my telegram account to find it had been stolen, sent a bunch of spam virtual currency ads and changed my name and avatar, I'm not sure if the session was the reason for the other person having full control access.

The biggest problem I have encountered so far is the /copy command for rclone. The /copy command copies cloud to cloud and when the copy is several hundred gigabytes, the copy does not complete in full and breaks, I have checked the logs and found no error codes.

**Comment by Sam-Max** [comment]
> 

String session stolen is not related to my bot, string session is not saved in anywhere someon else than you can access. You can check code.

Problem with copy I will check that.

**Comment by b1fly** [comment]
> > 
> 
> String session stolen is not related to my bot, string session is not saved in anywhere someon else can access but you. You can check code.
> 
> Problem with copy I will check that.

I turned on the two-step verification and so far so good.

I have a question, session_generator has the option to use bot generation when generating session strings, can this be used for premium account uploads and downloads? Or do I have to log in with my mobile number when generating the session string and then generate it.

I wish I could check the /copy command, it keeps breaking automatically, I don't understand why, I need to run the /copy command twice to continue copying, some files, even if I run the /copy command many times, it won't continue copying, there is no response.

**Comment by b1fly** [comment]
> > 
> 
> String session stolen is not related to my bot, string session is not saved in anywhere someon else can access but you. You can check code.
> 
> Problem with copy I will check that.

I've also noticed that I have a premium membership, but downloading videos from telegram using the /mirror command has slowed down to less than 1mb/s. I'm not sure if this has anything to do with the fact that the project has been updated several times.
