### ISSUE TITLE
Showing config menu

### ISSUE THREAD

**Issue by pachax001** [Sam-Max/Rclone-Tg-Bot#43]
Whenever I send a link or a telegram file ownerset command executes automatically.

**Comment by Sam-Max** [comment]
> Whenever I send a link or a telegram file ownerset command executes automatically.

Yes, it happens when you set sudo user, I will fix on next update

**Comment by Sam-Max** [comment]
> Whenever I send a link or a telegram file ownerset command executes automatically.

fixed

**Comment by pachax001** [comment]
> > Whenever I send a link or a telegram file ownerset command executes automatically.
> 
> fixed

Thanks
