### ISSUE TITLE
Status message error

### ISSUE THREAD

**Issue by pachax001** [Sam-Max/Rclone-Tg-Bot#46]
After files uploaded successfully to the onedrive the status message is showing
![Screenshot_20221001-175832_Plus](https://user-images.githubusercontent.com/93702860/193409876-126e80d2-fb80-4bd8-94ed-f00ba3d24294.jpg)

**Comment by Sam-Max** [comment]
Yes, I know I will improve status on next update

**Comment by Sam-Max** [comment]
@pachax001 Fixed
