### ISSUE TITLE
Deploying on Render

### ISSUE THREAD

**Issue by elricariocco** [Sam-Max/Rclone-Tg-Bot#7]
![image](https://user-images.githubusercontent.com/91217900/172026886-fad273b4-ed15-44d2-9454-c04909f80c0c.png)

Hello! I'm trying to deploy it this on Render and the bot is starting as intended but Render requires apps to return sucessful healthcheck response in order to mark the deploy as successful otherwise they stop the deploy after few mins. Does the app have a healthcheck endpoint? if not, maybe serving a "hello world" or some kind of message  (maybe your github profile as the creator of the repo) over https would be enough.
Or is there other way to circumvent this? Thanks in advance!

**Comment by Sam-Max** [comment]
> ![image](https://user-images.githubusercontent.com/91217900/172026886-fad273b4-ed15-44d2-9454-c04909f80c0c.png)
> 
> Hello! I'm trying to deploy it this on Render and the bot is starting as intended but Render requires apps to return sucessful healthcheck response in order to mark the deploy as successful otherwise they stop the deploy after few mins. Does the app have a healthcheck endpoint? if not, maybe serving a "hello world" or some kind of message (maybe your github profile as the creator of the repo) over https would be enough. Or is there other way to circumvent this? Thanks in advance!

Sorry bro, don't have time to check for this right now
